server:
  port: 8082

spring:
  application:
    name: admin-service
  security:
    user:
      name: disabled  
      password: disabled
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: preetam@123P

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyForDevelopmentOnlyChangeInProduction}
  expiration: 14400000 # 4 hours in milliseconds

logging:
  level:
    com.elowen.admin: DEBUG
